name: Build Jenkins AMI

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

jobs:
  merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Init
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: .
          command: init

      - name: Validate
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: .
          command: validate

      - name: echo secrets
        run: |
          echo "AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_SECRET_ACCESS_KEY = ${{ secrets.SSH_USERNAME }}"

      - name: Build
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: .
          target: jenkins-ami.pkr.hcl
          command: build
