name: Build Jenkins AMI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Init
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: .
          command: init

      - name: Build
        uses: hashicorp/packer-github-actions@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        with:
          working_directory: .
          target: jenkins-ami.pkr.hcl
          command: build
