name: Packer Validate

on:
  pull_request:
    branches: [main]

jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Packer Init
        run: packer init .

      - name: Packer Format Check
        run: packer fmt -check .

      - name: Packer Validate
        run: |
          packer validate .
