name: Packer Validate

on:
  pull_request:
    branches: [main]

jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Packer Init
        run: packer init .

      - name: Packer Format Check
        run: packer fmt -check . # Check if the packer files are properly formatted

      - name: echo secrets
        run: |
          echo "AWS_ACCESS_KEY_ID = ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_SECRET_ACCESS_KEY = ${{ secrets.SSH_USERNAME }}"

      - name: Debug AWS_ACCESS_KEY_ID presence
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID is empty"
          else
            echo "AWS_ACCESS_KEY_ID is set"
          fi

      - name: Debug AWS_SECRET_ACCESS_KEY presence
        run: |
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY is empty"
          else
            echo "AWS_SECRET_ACCESS_KEY is set"
          fi

      - name: Packer Validate
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          packer validate \
            -var "aws_account_id=${AWS_ACCOUNT_ID}" \
            -var "region=${AWS_REGION}" \
            -var "profile=${AWS_PROFILE}" \
            -var "ssh_username=${SSH_USERNAME}" \
            .
